### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by ghost** [anchorboat/EarthRetaliate#3]
Because the page probably won't need to be frequently updated and mostly static, can @buoyantair fill it up when you are free?

**Comment by elevenpassin** [comment]
Yeah, I'll do that when I am free. :P

**Comment by elevenpassin** [comment]
Haha We basically abandoned this whole project rip...

**Comment by ghost** [comment]
Yeah xD. Unless you still want to continue this? It's been almost a year and a half since I touched Ruby.
